config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.lrz.de/hpcsoftware/Peano:
      branch: p4
      repo: https://gitlab.lrz.de/hpcsoftware/Peano
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-scarlet-orangutan.sh
        container: qc.acc_nippy-azure-mammoth
  QC.Doc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-saffron-toad.sh
        container: qc.doc_woozy-seashell-capybara
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-platinum-tzu.sh
        container: qc.doc_gloppy-rust-gorilla
      gitlab.lrz.de/hpcsoftware/Peano markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-orange-sponge.sh
        container: qc.doc_stuffy-copper-caterpillar
  QC.Lic:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-heliotrope-axolotl.sh
        container: qc.lic_lousy-sapphire-burmese
  QC.Met:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amber-dragon.sh
        container: qc.met_beady-linen-fly
  QC.Sec:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-red-turtle.sh
        container: qc.sec_breezy-celadon-caiman
  QC.Sty:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-salmon-turkey.sh
        container: qc.sty_shaggy-pumpkin-tetra
      gitlab.lrz.de/hpcsoftware/Peano jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cornflower-dolphin.sh
        container: qc.sty_lanky-orange-chamois
      gitlab.lrz.de/hpcsoftware/Peano oclint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cornflower-corgi.sh
        container: qc.sty_goopy-aqua-malamute
  QC.Uni:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-rose-antelope.sh
        container: qc.uni_flabby-ochre-peccary
  QC.Ver:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-mauve-hippopotamus.sh
        container: qc.ver_sleazy-yellow-sponge
timeout: 5400
