config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.lrz.de/hpcsoftware/Peano:
      branch: p4
      repo: https://gitlab.lrz.de/hpcsoftware/Peano
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-pumpkin-chihuahua.sh
        container: qc.acc_bumpy-crimson-bulldog
  QC.Doc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-auburn-swan.sh
        container: qc.doc_nerdy-auburn-dolphin
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-linen-shark.sh
        container: qc.doc_leaky-brown-bandicoot
      gitlab.lrz.de/hpcsoftware/Peano markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-ecru-barb.sh
        container: qc.doc_stealthy-lemon-ladybird
  QC.Lic:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-harlequin-rattlesnake.sh
        container: qc.lic_geeky-lemon-flounder
  QC.Sec:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-buff-jaguar.sh
        container: qc.sec_queasy-copper-dachshund
  QC.Sty:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-denim-rattlesnake.sh
        container: qc.sty_homely-cobalt-neanderthal
  QC.Uni:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano pytest:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-chestnut-sloth.sh
        container: qc.uni_sunny-white-frigatebird
  QC.Ver:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-russet-quoll.sh
        container: qc.ver_wimpy-gamboge-dachsbracke
timeout: 5400
