config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.lrz.de/hpcsoftware/Peano:
      branch: p4
      repo: https://gitlab.lrz.de/hpcsoftware/Peano
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-yellow-stingray.sh
        container: qc.acc_lanky-vermilion-husky
  QC.Doc:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ochre-stoat.sh
        container: qc.doc_frumpy-cobalt-paradise
      gitlab.lrz.de/hpcsoftware/Peano git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-flax-warthog.sh
        container: qc.doc_leaky-celadon-ant
      gitlab.lrz.de/hpcsoftware/Peano markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ecru-oyster.sh
        container: qc.doc_messy-gold-devil
  QC.Lic:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chestnut-quoll.sh
        container: qc.lic_randy-harlequin-turkey
  QC.Sec:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-bistre-kiwi.sh
        container: qc.sec_surly-auburn-dhole
  QC.Sty:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-linen-anteater.sh
        container: qc.sty_hilly-turquoise-armadillo
      gitlab.lrz.de/hpcsoftware/Peano jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lemon-millipede.sh
        container: qc.sty_hilly-viridian-wombat
      gitlab.lrz.de/hpcsoftware/Peano oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-beige-weasel.sh
        container: qc.sty_scummy-chocolate-moose
  QC.Uni:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-yellow-quail.sh
        container: qc.uni_sloppy-persimmon-termite
  QC.Ver:
    repos:
      gitlab.lrz.de/hpcsoftware/Peano get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-green-yak.sh
        container: qc.ver_sloppy-persimmon-hippopotamus
timeout: 5400
